sonar.projectKey=wiphoo_Heroku-Buildpack-AWS_CodeArtifact_UV
sonar.organization=wiphoo-dev

# Source layout
sonar.sources=bin,lib
sonar.tests=test
sonar.test.inclusions=test/**
# Encoding of the source code
sonar.sourceEncoding=UTF-8

sonar.coverageReportPaths=coverage/coverage.xml

# Commands referenced by SonarCloud for documentation/dev reproduction
project.buildCommand=make check
project.testCommand=make check && make coverage
