name: Buildpack Builds

on:
  push:
  pull_request:

jobs:
  buildpack-builds:
    runs-on: ubuntu-latest
    env:
      HEROKU_STACK: ${{ vars.HEROKU_STACK }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pack
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.39.1/pack-v0.39.1-linux.tgz" -o /tmp/pack.tgz
          sudo tar -C /usr/local/bin -xzf /tmp/pack.tgz pack
          pack --version

      - name: Run generic integration build
        env:
          TEST_BUILDER: paketobuildpacks/builder-jammy-base
        run: test/integration.bash generic

      - name: Run Heroku integration build
        env:
          HEROKU_STACK: ${{ env.HEROKU_STACK }}
        run: test/integration.bash heroku
